version: "3.8"
services:
  frontend:
    build: frontend
    ports:
      - 3000:3000
  backend:
    build: backend
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://mongodb/web-scraping-db"
    ports:
      - 5000:5000
  mongodb:
    image: mongo
    ports:
      - 37017:27017
    volumes:
      - ./data:/data/db
